### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by wellls**

### CODE REVIEW

**Comment by tinbird125** [comment]
// LANGUAGE TRANSLATION TEMPLATE
// Includes all text within Ceri Launcher as of 1.8.0-beta

String translate(text) {
  switch (text) {
    //
    // ----- LOADING TEXT -----
    //

    case "getting app info":
      return “正在获取应用信息”;
    case "loading page":
      return “正在加载页面”;
    case "loading preferences":
      return “正在加载配置”;
    case "loading settings":
      return “正在加载设置”;

    //
    // ----- SETUP -----
    //

    case "Welcome to":
      return “欢迎使用”;
    case "Ceri Launcher":
      return “Ceri桌面”;

    case "Swipe left to start":
      return “左滑！让我们开始吧”;

    case "Select language":
      return “选择语言”;

    case "All languages (other than English) are translated by the community. Some translations may be incorrect or missing.":
      return “网友提供翻译，不足之处，敬请谅解。”;

    case "More languages coming soon":
      return “更多语言，敬请期待”;

    case "Choose your style":
      return “选择样式 ”;

    case "Choose style":
      return “样式设置”;

    case "All apps":
      return “全部应用”;

    case "Only favorites":
      return “仅收藏”;

    case "Tray":
      return “托盘样式”;

    case "You can always change this later":
      return “可在设置中进行更改”;

    case "Please choose an option to continue":
      return “选择一项配置以继续”;

    case "Choose your layout":
      return “选择桌面布局”;

    case "Choose layout":
      return “桌面布局”;

    case "Grid":
      return “宫格”;

    case "Honeycomb":
      return “蜂窝“;

    case "Choose your Ceri widget":
      return ”选择你的Ceri挂件“;

    case "Choose Ceri widget":
      return ”选择Ceri挂件“;

    case "None":
      return ”无“;

    case "Light analog":
      return ”白色时钟“;

    case "Dark analog":
      return ”暗色时钟“;

    case "Digital":
      return ”数字“;

    case "Assistant":
      return ”助手“;

    case "User widget":
      return ”应用挂件“;

    case "Choose your package":
      return ”选择安装包“;

    case "I'm an 18-year-old UK maths student trying to save money to study Cyber Security at university.":
      return ”我是谁？我今年18岁，来自英国，是一名数学系学生，目前正在努力存钱，打算去大学学习网络安全课程。“;
    case "If you want access to all features and you don't mind sparing £2, I would be incredibly grateful!":
      return ”仅需捐赠¥18元，就能解锁Ceri Launcher的全部功能，并且支持我的梦想，谢谢！“;

    case "Upgrade to pro":
      return ”升级专业版“;
    case "Support me and access all current and future features!":
      return ”支持我，解锁全部功能以及后续版本的更新！“;

    case "Restore purchase":
      return ”恢复购买“;
    case "Already supported the project?":
      return ”已赞助过此项目？“;

    case "Stay with free version":
      return ”我还是用免费版本吧“;
    case "Core functionality will always be free":
      return ”核心功能永久免费“;

    case "One last thing":
      return ”最后的最后“;

    case "I rely completely on user feedback to help make Ceri Launcher better.":
      return ”你的反馈非常有用，将会帮助我改进Ceri Launcher。“;
    case "Please consider joining":
      return ”请在Reddit搜索订阅Ceri Launcher，“;
    case "the Ceri Launcher subreddit":
      return ”加入我们的讨论组”;
    case "or sending me an email with your thoughts.":
      return “或者你有什么好点子，请给我发送邮件。”;
    case "I'd appreciate it a lot!":
      return “非常感谢！”;
    case "Hope you enjoy,":
      return “希望Ceri Launcher能给你带来不一样的体验！”;

    case "Tap anywhere":
      return ”点击屏幕“;
    case "to see your new home":
      return ”进入Ceri桌面“;

    //
    // ----- HOMESCREEN -----
    //

    case "Swipe down to search":
      return “下滑搜索”;

    case "Pull down to search":
      return “下拉搜索”;

    case "Long-press an app for options":
      return “长按可对应用进行设置”;

    case "Close":
      return “关闭”;

    case "Opens your Ceri Launcher settings":
      return “打开Ceri桌面设置”;

    case "Ceri Launcher Settings":
      return “Ceri桌面设置”;

    case "Add to favorites":
      return “添加收藏”;

    case "Remove from favorites":
      return “取消收藏”;

    case "Add back to homescreen":
      return “添加到桌面后返回”;

    case "Hide from homescreen":
      return “隐藏”;

    case "Application info":
      return “应用详情”;

    case "Uninstall":
      return “卸载”;

    //
    // ----- SEARCH -----
    //

    case "Search the web for":
      return ”在网络中搜索“;

    case "Search engine:":
      return ”搜索引擎“;

    //
    // ----- SETTINGS -----
    //

    case "Set as home":
      return “设为默认桌面”;
    case "Open default apps menu":
      return “打开默认桌面设置”;

    case "Device settings":
      return “系统设置”;
    case "Open the standard settings app":
      return “打开系统设置”;

    case "Style":
      return “样式”;
    case "Choose style (All apps, Only favorites, Tray), toggle app dimming":
      return “选择样式（显示全部应用，仅收藏，托盘显示），应用高亮;

    case "Wallpapers":
      return “壁纸“;
    case "Choose wallpaper, apply dim/vignette":
      return ”选择壁纸，应用高亮或弱光;

    case "Dark mode":
      return ”深色模式“;
    case "True dark mode for OLED devices\n(or #000000 lovers:":
      return ”OLED屏幕深色模式或纯黑模式“;

    case "Configure layout":
      return ”布局设置“;
    case "Standard grid or honeycomb, 2, 3 or 4 columns, customise icon size and padding":
      return ”标准、蜂窝、2、3、4列，自定义图标大小和间距“;

    case "Icon style":
      return ”图标样式“;
    case "Icon packs, shape, zoom/crop, shadows":
      return ”图标包、形状、大小或裁剪，阴影“;

    case "Search options":
      return ”搜索设置“;
    case "Search icon size, search engine":
      return ”搜索列表图标大小，搜索引擎“;

    case "Configure Ceri widget":
      return ”Ceri挂件设置“;
    case "Choose Ceri widget, configure padding":
      return ”选择Ceri挂件以及设置间距“;

    case "Scrolling animations":
      return ”滚动动画“;
    case "None, bubble, straight, inwards, outwards, and more":
      return ”无，气泡，平移，淡入，淡出，以及更多“;

    case "Notification dots":
      return ”图标通知角标“;
    case "See indications on your homescreen for pending notifications":
      return ”在桌面显示通知“;

    case "Gestures":
      return ”手势“;
    case "Launch apps and actions quickly with side gestures":
      return ”用手势启动应用或进行操作“;

    case "Miscellaneous settings":
      return ”其他设置“;
    case "Warning: Some of these may not have been fully tested":
      return ”注意：部分功能未经完全测试“;

    case "Performance options":
      return ”性能设置“;
    case "Experimental settings that may improve performance":
      return ”实验性功能可改善性能“;

    case "About Ceri Launcher":
      return ”关于Ceri桌面“;
    case "Version number, developer info":
      return ”应用版本与开发者信息“;

    case "Check for updates":
      return ”检查更新“;
    case "Check for Ceri Launcher updates on the Play Store":
      return ”在谷歌应用商店检查更新“;

    case "Support and feedback":
      return ”支持与反馈“;
    case "Go to the Ceri Launcher subreddit":
      return ”去Reddit查看Ceri Launcher订阅组“;

    case "Email developer":
      return ”发送邮件给开发者“;
    case "Have an issue or suggestion? Really enjoying Ceri Launcher? I try to reply within a few hours ::":
      return ”有疑问或建议？喜欢Ceri桌面？我将在数小时内回复你“;

    case "Change language":
      return ”更改语言“;
    case "Change the language for the Ceri Launcher interface":
      return ”更改Ceri桌面语言“;

    case "Add or improve translations":
      return ”新增或改进翻译“;
    case "Use your language skills to help make Ceri Launcher better. These translations will be added periodically in future updates.":
      return ”用你的语言帮助我们改善Ceri桌面，我们会在后期的更新中添加这些翻译“;

    case "Open source licenses":
      return ”开放源码许可证“;

    case "Version":
      return ”版本 1.9.10-测试版“; // context: "Version 1.7.5-beta" etc.
    case "Paid — thanks!":
      return ”支付成功，谢谢！“;
    case "Free version":
      return ”免费版“;
    case "Your own":
      return ”我的“;

    case "Ceri Wallpapers":
      return ”Ceri壁纸“;
    case "Android Home Xperience":
      return ”安卓桌面壁纸“;
    case "Tiles below 'Your own' will open the respective wallpaper album in your browser.":
      return ”「带有「我的」的标题选项需从系统中选择壁纸“;
    case "Vignette/dim":
      return ”高亮与亮度“;

    case "Dark mode":
      return ”深色模式“;
    case "Standard":
      return ”标准模式“;
    case "Black (OLED:":
      return ”OLED深色模式“;
    case "Automatic":
      return ”自动设置“;
    case "Dark mode off":
      return ”深色模式关闭“;
    case "Dark mode on":
      return ”深色模式打开“;
    case "Dark mode enables at night":
      return ”在夜晚打开深色模式“;

    case "Miscellaneous":
      return ”其他设置“;
    case "Disable haptics":
      return ”关闭触摸反馈“;
    case "Show package names in search":
      return ”在搜索中显示应用包名“;
    case "Disable vignette":
      return ”关闭应用高亮“;
    case "Disable scrolling beyond screen height":
      return ”关闭滑动超出屏幕“;

    case "2 columns":
      return ”两列“;
    case "3 columns":
      return ”三列“;
    case "Icon size":
      return ”图标大小“;
    case "Icon padding":
      return ”图标间距“;
    case "Standard grid layout":
      return ”标准宫格布局“;
    case "Honeycomb layout":
      return ”蜂窝布局“;
    case "Favorites stay at the top":
      return ”收藏应用置顶“;
    case "Just your favorites, nothing else":
      return ”仅展示收藏“;
    case "Automatically show your most used apps only":
      return ”自动展示常用应用“;
    case "(experimental:":
      return ”（实验功能：“;
    case "Dim apps that aren't in favorites":
      return ”弱化显示非收藏应用“;

    case "Nothing set":
      return ”未作出任何设置“;
    case "Select package":
      return ”选择应用程序“;
    case "Actions will be launchable with gestures in an upcoming update.":
      return ”未来的更新中将增加手势操作“;
    case "Search":
      return “搜索”;

    case "No icon packs found.":
      return “未找到图标包”;
    case "None (default:":
      return “无（默认：”;
    case "Select icon pack":
      return “选择图标包”;
    case "If you have an icon pack installed, choose it here":
      return “在此选择已安装的图标包”;

    case "Corner radius":
      return “圆角大小”;
    case "Zoom/crop":
      return “大小和裁剪”;
    case "Shadows (off:":
      return “阴影（关闭：”;
    case "Shadows (subtle:":
      return ”阴影（轻：“;
    case "Shadows (heavy:":
      return “阴影（重：”;
    case "Shadows (heavier:":
      return “阴影（较重：”;

    case "App icon size":
      return “应用图标大小”;

    case "Animation strength":
      return “动画强度”;
    case "disabled":
      return “已禁用”;
    case "weak":
      return “弱”;
    case "normal":
      return “正常”;
    case "strong":
      return “强”;
    case "strongest":
      return “极强”;

    case "These are EXPERIMENTAL settings to try out if you suffer from poor performance or extreme battery drain when using Ceri Launcher.":
      return “若出现耗电或卡顿现象，可启用实验功能进行改进”;
    case "If you are not having issues with performance it is recommended that you leave these at their defaults.":
      return “若性能设置后未出现问题，建议不要再进行改动”;
    case "Icon render size":
      return “图标渲染大小”;
    case "Default is 192. Smaller values should result in lower RAM usage (at the expense of image quality:.":
      return “默认值：192。值较小可减少内存消耗（但会降低图片质量：”;
    case "EXAMPLE":
      return “例子”;
    case "Remove icons out of frame":
      return “裁剪图标中超出框架的部分”;
    case "Disable antialiasing":
      return “禁用抗锯齿”;
    case "Force icon caching":
      return “强制使用图标缓存”;

    case "Ceri Launcher utilizes the works of these people:":
      return “这些人的工作对Ceri Launcher有很大的帮助：：”;

    case "EXPERIMENTAL.":
      return ”实验功能。“;

    case "Nothing":
      return ”空“;
    case "Light analog clock widget":
      return ”浅色模拟时钟“;
    case "by NPKompleet, The CS Guy and Ali Sayed":
      return ”by NPKompleet，Ali Sayed以及服务端开发者“;
    case "Dark analog clock widget":
      return ”深色模拟时钟“;
    case "Digital clock":
      return ”数字时钟“;

    //
    // ----- WIDGETS -----
    //

    case "Monday":
      return ”星期一“;
    case "Tuesday":
      return ”星期二“;
    case "Wednesday":
      return ”星期三“;
    case "Thursday":
      return ”星期四“;
    case "Friday":
      return ”星期五“;
    case "Saturday":
      return ”星期六“;
    case "Sunday":
      return ”星期日“;

    case "January":
      return ”1月“;
    case "February":
      return ”2月“;
    case "March":
      return ”3月“;
    case "April":
      return ”4月“;
    case "May":
      return ”5月“;
    case "June":
      return ”6月“;
    case "July":
      return ”7月“;
    case "August":
      return ”8月“;
    case "September":
      return ”9月“;
    case "October":
      return ”10月“;
    case "November":
      return ”11月“;
    case "December":
      return ”12月“;

    case "Good morning":
      return ”早上好！“;
    case "Good afternoon":
      return ”下午好！“;
    case "Good evening":
      return ”晚上好！“;
    case "Sleep well":
      return ”晚安，好梦！“;
  }

  return ”text“; // return original text if no translation found
}

**Comment by tinbird125** [comment]
I don't know how to save my edit, so I duplicated them here, hoping the Chinese-Simplified language would be supported in future versions.

**Comment by wellls** [comment]
> I don't know how to save my edit, so I duplicated them here, hoping the Chinese-Simplified language would be supported in future versions.

如果你愿意的话，我将你的翻译版本 merge 进我的 branch 中，然后再向作者发起 pull request.

**Comment by tinbird125** [comment]
Of course , you can, it's a good project, I want it widespread.

**Comment by wellls** [comment]
> Of course , you can, it's a good project, I want it widespread.

I have merge our translations, you can check in this commit, https://github.com/jckpn/CeriLauncher/pull/9/commits/32f10f4f1c7e3fa3e12f2820616b408d26ff802f . Now just wait for the author to access our pull request.

**Comment by jckpn** [comment]
Added! Thanks so much @wellls and @tinbird125

**Pull request merged**
