### PR TITLE
Update translations.txt

### PR DESCRIPTION
**Pull request by hazae41**

### CODE REVIEW

**Comment by jckpn** [comment]
Thanks @hazae41!

**Comment by tinbird125** [comment]
Hello,I am a Chinese user of Ceri Laugcher,I love this fabulous laugcher, and I want to contribute to translate the language to my language.Could I?And how should do this work?

**Comment by jckpn** [comment]
Hi,

Thanks for your interest in helping to translate Ceri Launcher!

I created a new file for Chinese translations:
https://github.com/jckpn/CeriLauncher/tree/master/translations

Instructions for adding translations can be found here:
https://github.com/jckpn/CeriLauncher/blob/master/README.md

Let me know if you have any questions.

Thanks again!
Jack

**Comment by tinbird125** [comment]
Hi，I met some problems while translating， the descriptions of some options quite confuse me, such as  “Disable scrolling beyond screen height”，what if we just describe the effect after applied the option, and make a toggle to switch it, like "Scrolling beyond screen height". Perhaps it’s just the difference between two languages?LOL

On Nov 16, 2019, at 4:39 AM, Jack Paine <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Thanks for your interest in helping to translate Ceri Launcher!

I created a new file for Chinese translations:
https://github.com/jckpn/CeriLauncher/tree/master/translations

Instructions for adding translations can be found here:
https://github.com/jckpn/CeriLauncher/blob/master/README.md

Let me know if you have any questions.

Thanks again!
Jack

**Comment by tinbird125** [comment]
Oh，I’m sorry to bother you again, I almost forget that I want some screenshots of the Pro version to understand the text further, because I unable to upgrade the version by Google Pay in my country.Can you send me some?

On Nov 16, 2019, at 10:16 PM, Tinbird . <straw1225@hotmail.com<mailto:straw1225@hotmail.com>> wrote:

Hi，I met some problems while translating， the descriptions of some options quite confuse me, such as  “Disable scrolling beyond screen height”，what if we just describe the effect after applied the option, and make a toggle to switch it, like "Scrolling beyond screen height". Perhaps it’s just the difference between two languages?LOL

On Nov 16, 2019, at 4:39 AM, Jack Paine <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

Thanks for your interest in helping to translate Ceri Launcher!

I created a new file for Chinese translations:
https://github.com/jckpn/CeriLauncher/tree/master/translations

Instructions for adding translations can be found here:
https://github.com/jckpn/CeriLauncher/blob/master/README.md

Let me know if you have any questions.

Thanks again!
Jack

**Comment by jckpn** [comment]
Hey, thanks for your effort! Here's a promo code for the Pro
version: S8Q07DNXSKVDWNVL5H8KYFD (instructions:
https://support.google.com/googleplay/answer/3422659?hl=en-GB)

Hopefully that helps :) If that doesn't work I'll send over some
screenshots.

Don't worry too much about getting the translations perfect, as long as
they're understandable people will be very grateful!

Thanks,
Jack

**Pull request merged**
